Repository cofide/cofide-api-sdk, pull requests merged in 2025-03, with the labels that each got.

#48 fix: A few small changes to Federation and FederationService
  gen/go/proto/connect/federation_service/v1alpha1/federation_service.pb.go
  gen/go/proto/connect/federation_service/v1alpha1/federation_service_grpc.pb.go
  gen/go/proto/federation/v1alpha1/federation.pb.go
  proto/connect/federation_service/v1alpha1/federation_service.proto
  proto/federation/v1alpha1/federation.proto
Labels: buf skip breaking

#63 feat: `GetTrustZone` rpc added to the `TrustZoneService`
  gen/go/proto/connect/trust_zone_service/v1alpha1/trust_zone_service.pb.go
  gen/go/proto/connect/trust_zone_service/v1alpha1/trust_zone_service_grpc.pb.go
  pkg/connect/client/trustzone/v1alpha1/trustzone.go
  pkg/connect/client/trustzone/v1alpha1/trustzone_test.go
  proto/connect/trust_zone_service/v1alpha1/trust_zone_service.proto
Labels: feature

#61 feat: move attestation policy bindings and federations from TrustZone to Config
  proto/config/v1alpha1/config.proto
  proto/trust_zone/v1alpha1/trust_zone.proto
Labels: feature

#64 feat: add federation to clientset and add fake
  gen/go/proto/config/v1alpha1/config.pb.go
  gen/go/proto/connect/federation_service/v1alpha1/federation_service.pb.go
  gen/go/proto/connect/federation_service/v1alpha1/federation_service_grpc.pb.go
  gen/go/proto/trust_zone/v1alpha1/trust_zone.pb.go
  pkg/connect/client/clientset.go
  pkg/connect/client/clientset_test.go
  pkg/connect/client/fake/client/fakeclient.go
  pkg/connect/client/fake/connect/fakeconnect.go
  pkg/connect/client/federation/v1alpha1/fake/fake.go
  pkg/connect/client/federation/v1alpha1/fake/fake_test.go
  pkg/connect/client/federation/v1alpha1/federation.go
  pkg/connect/client/federation/v1alpha1/federation_test.go
  proto/connect/federation_service/v1alpha1/federation_service.proto
Labels: feature

#68 fix: Update `APBindingClient` name
  pkg/connect/client/clientset.go
  pkg/connect/client/clientset_test.go
  pkg/connect/client/fake/client/fakeclient.go
Labels: bug
