Repository cofide/cofide-api-sdk, pull requests merged in 2025-04, with the labels that each got.

#73 feat: add trust_zone_names field to provision plugin deploy and tear_down
  gen/go/proto/provision_plugin/v1alpha1/plugin.pb.go
  gen/ts/proto/provision_plugin/v1alpha1/plugin_pb.ts
  proto/provision_plugin/v1alpha1/plugin.proto
Labels: feature

#36 Remove status in RPC response messages
  gen/go/proto/connect/agent_service/v1alpha1/agent_service.pb.go
  gen/go/proto/connect/trust_zone_service/v1alpha1/trust_zone_service.pb.go
  gen/ts/proto/connect/agent_service/v1alpha1/agent_service_pb.ts
  gen/ts/proto/connect/trust_zone_service/v1alpha1/trust_zone_service_pb.ts
  proto/connect/agent_service/v1alpha1/agent_service.proto
  proto/connect/trust_zone_service/v1alpha1/trust_zone_service.proto
Labels: buf skip breaking

#76 feat: add destroy RPCs to DataSourcePluginService
  gen/go/proto/cofidectl_plugin/v1alpha1/plugin.pb.go
  gen/go/proto/cofidectl_plugin/v1alpha1/plugin_grpc.pb.go
  gen/go/proto/cofidectl_plugin/v1alpha1/v1alpha1connect/plugin.connect.go
  gen/ts/proto/cofidectl_plugin/v1alpha1/plugin_pb.ts
  proto/cofidectl_plugin/v1alpha1/plugin.proto
Labels: feature

#75 feat: add DestroyTrustZone RPC to TrustZoneService
  gen/go/proto/connect/trust_zone_service/v1alpha1/trust_zone_service.pb.go
  gen/go/proto/connect/trust_zone_service/v1alpha1/trust_zone_service_grpc.pb.go
  gen/go/proto/connect/trust_zone_service/v1alpha1/v1alpha1connect/trust_zone_service.connect.go
  gen/ts/proto/connect/trust_zone_service/v1alpha1/trust_zone_service_pb.ts
  pkg/connect/client/trustzone/v1alpha1/fake/fake.go
  pkg/connect/client/trustzone/v1alpha1/fake/fake_test.go
  pkg/connect/client/trustzone/v1alpha1/trustzone.go
  pkg/connect/client/trustzone/v1alpha1/trustzone_test.go
  proto/connect/trust_zone_service/v1alpha1/trust_zone_service.proto
Labels: feature

#77 chore: remove deprecated RPCs in TrustZoneService
  gen/go/proto/connect/trust_zone_service/v1alpha1/trust_zone_service.pb.go
  gen/go/proto/connect/trust_zone_service/v1alpha1/trust_zone_service_grpc.pb.go
  gen/go/proto/connect/trust_zone_service/v1alpha1/v1alpha1connect/trust_zone_service.connect.go
  gen/ts/proto/connect/trust_zone_service/v1alpha1/trust_zone_service_pb.ts
  pkg/connect/client/trustzone/v1alpha1/fake/fake_test.go
  pkg/connect/client/trustzone/v1alpha1/trustzone.go
  pkg/connect/client/trustzone/v1alpha1/trustzone_test.go
  proto/connect/trust_zone_service/v1alpha1/trust_zone_service.proto
Labels: buf skip breaking, chore

#71 Add Node & Selector types, client and service for trust-zone-server
  README.md
  gen/go/proto/connect/datastore_service/v1alpha1/datastore.pb.go
  gen/go/proto/connect/datastore_service/v1alpha1/datastore_service.pb.go
  gen/go/proto/connect/datastore_service/v1alpha1/datastore_service_grpc.pb.go
  gen/go/proto/connect/datastore_service/v1alpha1/v1alpha1connect/datastore_service.connect.go
  gen/ts/proto/connect/datastore_service/v1alpha1/datastore_pb.ts
  gen/ts/proto/connect/datastore_service/v1alpha1/datastore_service_pb.ts
  pkg/connect/client/clientset.go
  pkg/connect/client/clientset_test.go
  pkg/connect/client/datastore/v1alpha1/datastore.go
  pkg/connect/client/datastore/v1alpha1/datastore_test.go
  pkg/connect/client/datastore/v1alpha1/fake/fake.go
  pkg/connect/client/datastore/v1alpha1/fake/fake_test.go
  pkg/connect/client/fake/client/fakeclient.go
  pkg/connect/client/fake/connect/fakeconnect.go
  proto/connect/datastore_service/v1alpha1/datastore.proto
  proto/connect/datastore_service/v1alpha1/datastore_service.proto
Labels: chore

#80 fix: use map instead of list for selectors
  gen/go/proto/connect/datastore_service/v1alpha1/datastore_service.pb.go
  gen/ts/proto/connect/datastore_service/v1alpha1/datastore_service_pb.ts
  pkg/connect/client/datastore/v1alpha1/datastore_test.go
  pkg/connect/client/datastore/v1alpha1/fake/fake.go
  pkg/connect/client/datastore/v1alpha1/fake/fake_test.go
  proto/connect/datastore_service/v1alpha1/datastore_service.proto
Labels: bug, buf skip breaking
